version: '3'
services:
  api:
    image: your-api-image:latest
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - APP_ENV=production
    restart: always

  db:
    image: postgres:latest

networks:
  default:
    external:
      name: network-stack-name-nestjsapp
